from conans import ConanFile, CMake, tools


class GLFWConan(ConanFile):
    name = "volt_gl"
    version = "0.0.1"
    license = "GPL3"
    author = ""
    url = "https://github.com/SirHall/volt_gl"
    requires = []
    description = "OpenGL loader generated by dav1d's GLAD"
    topics = ("graphics", "glad", "opengl")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}
    generators = "cmake"
    exports_sources = "include/**"

    def source(self):
        git = tools.Git(folder="volt_gl")
        git.clone("https://github.com/SirHall/volt_gl.git", branch="master", shallow=True)

        # This small hack might be useful to guarantee proper /MT /MD linkage
        # in MSVC if the packaged project doesn't have variables to set it
        # properly
        tools.replace_in_file("volt_gl/CMakeLists.txt", "project(volt_ge_gl)",
                              '''project(volt_ge_gl)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()''')

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder="volt_gl")
        cmake.build()

        # Explicit way:
        # self.run('cmake %s/hello %s'
        #          % (self.source_folder, cmake.command_line))
        # self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self.copy("*.h", dst="include/",
                  src="volt_gl/volt_gl/include/", keep_path=True)
        self.copy("*.hpp", dst="include/",
                  src="volt_gl/volt_gl/include/", keep_path=True)
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["volt_gl"]
